[tox]
envlist = py312-django42, custom-user, quality

[testenv]
package = wheel
extras = test
deps = Django==4.2.20
commands =
    python -m django check --settings=tests.settings
    python -m pytest {posargs}

[testenv:custom-user]
commands = python -m pytest --ds=tests.custom_settings tests/custom_model_cases.py

[testenv:quality]
extras = quality
deps =
    Django==4.2.20
    tutor>=20,<21
setenv =
    PYLINTHOME = {envtmpdir}/pylint
commands =
    python -m pylint openedx_account_lock_ext tutoraccountlock
    python -m pycodestyle --max-line-length=120 openedx_account_lock_ext tutoraccountlock tests
    python -m pydocstyle openedx_account_lock_ext tutoraccountlock
    python -m isort --check-only --diff openedx_account_lock_ext tutoraccountlock tests
    python -m mypy openedx_account_lock_ext

[pycodestyle]
max-line-length = 120
